version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - checkout # check out the code in the project directory
      - run: wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
      - run: apt-get update && apt install --yes ./google-chrome-stable_current_amd64.deb
      - run: yarn install
      - run: yarn ng build --prod
      - run: yarn ng e2e
      - run: echo "hello world" # run the `echo` command