version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - checkout # check out the code in the project directory
      - run: yarn ng build --prod
      - run: yarn ng e2e
      - run: echo "hello world" # run the `echo` command